#!/bin/bash
# ;;/;&
# use exit code 64 to reboot system on exit
notify(){
  logger -t $app "$*"
  echo "$*"
}
app=SYSUPDATE
etver=$(cat /etc/etransver)
updated=false
case "$etver" in
20180322)
  notify "Updating to v.20180328"
  apt-get update && apt-get install -y ntp pps-tools
  if [ $? -eq 0 ]
  then
    updated=true
    systemctl disable systemd-timesyncd
    systemctl stop systemd-timesyncd
    file="/etc/ntp.conf"
    echo -e "# GPS Serial data reference (NTP0)" >> $file
    echo -e "server 127.127.28.0 minpoll 4 maxpoll 4" >> $file
    echo -e "fudge 127.127.28.0 refid GPS\n" >> $file
    echo -e "# GPS PPS reference (NTP1)" >> $file
    echo -e "server 127.127.28.1 minpoll 4 maxpoll 4 prefer" >> $file
    echo -e "fudge 127.127.28.1 refid PPS" >> $file
    service ntp restart
    echo "20180328" > /etc/etransver
    notify "Updated to v.20180328"
  else
    notify "Update to v.20180328 failed"
    exit 1
  fi
  ;&
20180328)
  notify "Updating to v.20180330"
  sed -i -- 's/GPSD_OPTIONS=""/GPSD_OPTIONS="-n"/g' /etc/default/gpsd
  service gpsd restart
  echo "20180330" > /etc/etransver
  notify "Updated to v.20180330"
  exit 0
  ;;
*)
  notify "Unknown local version: $etver. Exit"
  exit 1  
esac
exit 0
