#!/bin/bash
# ;;/;&
# use exit code 64 to reboot system on exit
notify(){
  logger -t $app "$*"
  echo "$*"
}


check_update(){
  if [ $updated -eq 0 ]
  then
    apt-get update
    if [ $? -eq 0 ]
    then
      updated=1    
    else
      notify "Update to v.$1 failed in updating packages"
      exit 1
    fi
  fi

}

app=SYSUPDATE
etver=$(cat /etc/etransver)
updated=0
case "$etver" in
20180322)
  notify "Updating to v.20180328"
  check_update 20180328
  apt-get install -y ntp pps-tools
  if [ $? -eq 0 ]
  then
    systemctl disable systemd-timesyncd
    systemctl stop systemd-timesyncd
    file="/etc/ntp.conf"
    echo -e "# GPS Serial data reference (NTP0)" >> $file
    echo -e "server 127.127.28.0 minpoll 4 maxpoll 4" >> $file
    echo -e "fudge 127.127.28.0 refid GPS\n" >> $file
    echo -e "# GPS PPS reference (NTP1)" >> $file
    echo -e "server 127.127.28.1 minpoll 4 maxpoll 4 prefer" >> $file
    echo -e "fudge 127.127.28.1 refid PPS" >> $file
    service ntp restart
    echo "20180328" > /etc/etransver
    notify "Updated to v.20180328"
  else
    notify "Update to v.20180328 failed - ntp install"
    exit 1
  fi
  ;&
20180328)
  notify "Updating to v.20180330"
  sed -i -- 's/GPSD_OPTIONS=""/GPSD_OPTIONS="-n"/g' /etc/default/gpsd
  service gpsd restart
  echo "20180330" > /etc/etransver
  notify "Updated to v.20180330"
  ;&
20180330)
  notify "Updating to v.20180405"
  service ntp disable
  service ntp stop
  systemctl enable systemd-timesyncd
  systemctl start systemd-timesyncd
  dpkg -l | grep sqlite3 > /dev/null
  if [ $? -ne 0 ]
  then
    check_update 20180405
    apt-get install sqlite3
    if [ $? -ne 0 ]
    then
      notify "Update to v.20180405 failed - sqlite3 install"
      exit 1
    fi
  fi
  if [ ! -x /usr/bin/cgps ]
  then
    wget -q --no-cache -P /usr/bin https://storage.googleapis.com/etranspi-update/sysfiles/cgps
    if [ $? -ne 0 ]
    then
      notify "Update to v.20180405 failed - cgps install"
      exit 1
    fi
    chown root:root /usr/bin/cgps
    chmod +x /usr/bin/cgps
  fi
  if [ ! -x /usr/bin/cgps ]
  then
    wget -q --no-cache -P /usr/bin https://storage.googleapis.com/etranspi-update/sysfiles/gpspipe
    if [ $? -ne 0 ]
    then
      notify "Update to v.20180405 failed - gpspipe install"
      exit 1
    fi
    chown root:root /usr/bin/gpspipe
    chmod +x /usr/bin/gpspipe
  fi  
  
  echo "20180330" > /etc/etransver
  ;;
*)
  notify "Unknown local version: $etver. Exit"
  exit 1  
esac
exit 0
