#!/bin/bash
# ;;/;&
# use exit code 64 to reboot system on exit
notify(){
  logger -t $app "$*"
  echo "$*"
}


check_update(){
  if [ $updated -eq 0 ]
  then
    apt-get update
    if [ $? -eq 0 ]
    then
      updated=1    
    else
      notify "Update to v.$1 failed in updating packages"
      exit 1
    fi
  fi

}

app=SYSUPDATE
if [ "$(id -u)" != "0" ]; then
	notify "Not root"
	exit 1
fi
etver=$(cat /etc/etransver)
updated=0
case "$etver" in
20180505)
#  does not exist, just for fallthrough
#  notify "Updating to v.20180606"
#  check_update 20180606
#  echo "20180606" > /etc/etransver
  ;&
20180613)
  notify "Updating to v.20180911"
  check_update 20180911
  apt-get install -y pigpio python-pigpio python3-pigpio && sed -i -- 's/pigpiod -l/pigpiod/g' /lib/systemd/system/pigpiod.service && systemctl enable pigpiod.service && systemctl start pigpiod.service && sed -i -- 's/20180613/20180911/g' /etc/etransver  
  ;;
*)
  notify "Unknown local version: $etver. Exit"
  exit 1  
esac
exit 0
