#!/bin/bash
source /usr/local/conf/tunnel/tunnel
if [ $? -ne 0 ]
then
  exit 1
fi
ssh -N -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o IdentityFile=/usr/local/conf/tunnel/id_rsa -R "$TURL:$TPORT:localhost:22" "tunnel@$TURL"

