#!/bin/bash

#fork!!! uses blocking functions!

syncFlag="/tmp/timeSynced"
while true
do
  ntpdate -s pool.ntp.org
  if [ $? -eq 0 ]
  then
    logger -t NTPSYNC "Time Sync success"
    if [ ! -e "$syncFlag" ]
    then
      touch "$syncFlag"
      clocks save
    fi
    break
  else
    sleep 5
  fi
done
