#!/bin/bash
syncFlag="/tmp/syncOK"
ntpdate -s pool.ntp.org
if [ $? -eq 0 ]
then
  logger -t NTPSYNC "Time Sync success"
  /usr/local/conf/clocks save
  if [ ! -e "$syncFlag" ]
  then
    echo "ntp" > "$syncFlag"
  fi
else
  exit 1
fi

