#!/bin/bash

# operates in HOME of user under which is started!
# should be started under etrans?


notify(){
#  logger -t $app "$*"
  echo "$*"
}

clean_tmp(){
  notify "Cleaning temp..."
  rm -rf /tmp/etran*
}

update_from_tmp(){
  if [ -e "$homeDir/etrans.zip" ]
  then
    mv -f "$homeDir/etrans.zip" "$homeDir/old.etrans.zip"
  fi
  ps ux | grep -P 'Duser\.timezone' | grep -v 'grep' > /dev/null
  if [ $? -eq 0 ]
  then
    notify "App running, stopping..."
    runned=true
    send2port 41000 stop_all
    sleep 5
    pkill -f java
  else
    runned=false
  fi
  rm -f "$homeDir/etrans/base/*.jar"
  rm -f "$homeDir/etrans/gps/*.jar"
  rm -f "$homeDir/etrans/control/*.jar"
  rm -f "$homeDir/etrans/cam/*.jar"
  rm -f "$homeDir/etrans/lib/components*.jar"
  cp -r /tmp/etrans "$homeDir"
  mv /tmp/etrans.zip "$homeDir"
  clean_tmp
  notify "App update success"
  if [ $runned = true ]
  then
    notify "Starting previously run app..."
    "$homeDir/etrans/./app_start"
  fi
}

download_and_extract_libs(){
  listFile="/tmp/etrans/libs.txt"
  urlPrefix="https://storage.googleapis.com/etranspi-update/libs"
  destination=/tmp/etrans/lib
  currentList=$(ls etrans/lib)
  res=0;
  if [ -e $listFile ]
  then
    while IFS='' read -r line || [[ -n "$line" ]]; do
      result="$(echo $currentList | grep $line)"
      if [ $? -ne 0 ]
      then
        notify "Lib $line missing, starting download..."
        wget -P $destination "$urlPrefix/$line"
        if [ $? -eq 0 ]
        then
          notify "$line : download ok"
        else
          notify "$line : download failed. Update aborted"
          clean_tmp
        fi
      fi
    done < "$listFile"
    update_from_tmp
  else
    notify "No libs list file detected, list verification impossible, aborting update"
    clean_tmp
  fi  
}

extract_files(){
  7z x /tmp/etrans.zip -p$arch_pwd -y -o/tmp
  if [ $? -eq 0 ]
  then
    notify "App extract ok"
    download_and_extract_libs
  else
    notify "Extract failure - check achive and/or password!"
    clean_tmp
  fi
}

download_and_extract_app(){
  wget -q --no-cache -P /tmp "$baseURL/etrans.zip"
  if [ $? -eq 0 ]
  then
    #if download success
    notify "App dowload success, extracting..."
    extract_files
  else
    notify "App dowload failure - check if connection is ok and archive is available remotely!"
    clean_tmp
  fi
}

update_app(){
  #software deployment
  #app part
  baseURL="https://raw.githubusercontent.com/etransny/etransny-pit-app-$bldSelect/master"
  tmp=$(wget --no-cache -qO- "$baseURL/etrans.md5")
  if [ $? -ne 0 ]
  then
    notify "No remote checksum file - exit"
  else
    newMD5=$(echo $tmp | grep -Po '^\w*')
    if [ -z $newMD5 ]
    then
      notify "No checksum data in remote file - exit"
    else
      #download and process app archive only if checksums do not match!
      if [ -e "$homeDir/etrans.zip" ]
      then
        appMD5=$(md5sum "$homeDir/etrans.zip" | grep -Po '^\w*');
        notify "remote app archive checksum: $newMD5"
        notify "local app archive checksum: $appMD5"
        if [ "$appMD5" != "$newMD5" ]
        then
          notify "Checksums differ, starting download..."
          download_and_extract_app
        else
          notify "Local and remote app archives match - no update needed"
        fi
      else
        notify "No local app archive - starting force download"
        download_and_extract_app
      fi
    fi
  fi
}


app="ETRANS_CLIENT_UPDATER"
homeDir=$(eval echo "~/")
bldTypeFile="$homeDir/etappbuild"
arch_pwd=$1
if [ -z "$arch_pwd" ]
then
  notify "Password not provided. Update aborted"
  exit 0
fi
# cli build type argument overrides default and/or file-read value
bldSelect=$2
# if cli built type not provided, first we look for "type" file with build type set
if [ -z "$bldSelect" ]
then
  if [ -f "$bldTypeFile" ]
  then
    bldSelect=$(head -n 1 "$bldTypeFile")
    if [ -z "$bldSelect" ]
    then
      bldSelect="prod"      
    fi
  else
    bldSelect="prod"
  fi
fi
case "$bldSelect" in
	special | dev | prod)
	  notify "Deploy type [$bldSelect] selected!"
		update_app
		;;
	*)
		notify "Exit. Unknown deploy type [$bldSelect] provided"
esac

